/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DataElementsModule"
 * 	found in "./DataElementsModule.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_WaitOnStopLine_H_
#define	_WaitOnStopLine_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WaitOnStopLine */
typedef BOOLEAN_t	 WaitOnStopLine_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaitOnStopLine;
asn_struct_free_f WaitOnStopLine_free;
asn_struct_print_f WaitOnStopLine_print;
asn_constr_check_f WaitOnStopLine_constraint;
ber_type_decoder_f WaitOnStopLine_decode_ber;
der_type_encoder_f WaitOnStopLine_encode_der;
xer_type_decoder_f WaitOnStopLine_decode_xer;
xer_type_encoder_f WaitOnStopLine_encode_xer;
oer_type_decoder_f WaitOnStopLine_decode_oer;
oer_type_encoder_f WaitOnStopLine_encode_oer;
per_type_decoder_f WaitOnStopLine_decode_uper;
per_type_encoder_f WaitOnStopLine_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _WaitOnStopLine_H_ */
#include <asn_internal.h>
